###服务端口号
server:
  port: 8003
###eureka 基本信息配置
eureka:
  instance:
    ###注册到eurekaip地址
    hostname: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8001/eureka
    ###因为自己是为注册中心，不需要自己注册自己
    register-with-eureka: true
    ###因为自己是为注册中心，不需要检索服务
    fetch-registry: true
spring:
  application:
    name: server_system
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/movies_online?characterEncoding=UTF8&autoReconnect=true
    username: root
    password: 123456
    name: movice_online
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:/mapper/*.xml
#    type: com.alibaba.druid.pool.DruidDataSource
logging:
  level:
    com.gzmu.mapper: trace
