spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/movies_online?characterEncoding=UTF8&autoReconnect=true
    username: root
    password: 123456
    name: movice_online
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:/mapper/*.xml
#    type: com.alibaba.druid.pool.DruidDataSource
logging:
  level:
    com.gzmu.server.mapper: trace
